import pyautogui as insta

insta.press ("win")
insta.sleep (2)
insta.write ("instagram")
insta.sleep(2)
insta.press ("enter")
insta.sleep (2)
insta.moveTo(235,366)
insta.click()
insta.sleep (2)
insta.write ("email")
insta.sleep (2)
insta.press("tab")
insta.sleep(2)
insta.write("usuario")
insta.press("tab")
insta.write("senha")
insta.press ("tab")
insta.press("enter")
